---
apiVersion: v1
kind: Service
metadata:
  name: webapp-api
  labels:
    app: webapp-api
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: webapp-api
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp-api
  labels:
    app: webapp-api
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webapp-api
        tier: backend
    spec:
      containers:
        - image: 533616270150.dkr.ecr.us-east-1.amazonaws.com/webapp-api:latest
          #- image: CONTAINER_IMAGE
          imagePullPolicy: Always
          name: webapp-api
          env:
            - name: REDIS_IP
              valueFrom:
                secretKeyRef:
                  name: demo-credentials
                  key: host
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: demo-credentials
                  key: port
          ports:
            - containerPort: 8080
