apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: webapp-api
    namespace: session-cluster-demo
    annotations:
      kubernetes.io/ingress.class: "nginx"
  spec:
    rules:
      - host: staging.jingood2.me.uk
        http:
          paths:
            - backend:
                serviceName: webapp-api
                servicePort: 80
              path: /
